CREATE DATABASE IF NOT EXISTS eco_scambio;
USE eco_scambio;

CREATE TABLE IF NOT EXISTS UTENTI (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NICK VARCHAR(20) NOT NULL UNIQUE CHECK (CHAR_LENGTH(NICK) BETWEEN 4 AND 20),
    PASSWORD VARCHAR(255) NOT NULL CHECK (CHAR_LENGTH(PASSWORD) BETWEEN 4 AND 255),
    ARTIGIANO BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS DATI_AZIENDE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_UTENTE INT NOT NULL,
    RAGIONE VARCHAR(30),
    ADDRESS2 VARCHAR(255),
    TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_UTENTE) REFERENCES UTENTI(ID)
);

CREATE TABLE IF NOT EXISTS DATI_ARTIGIANI (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_UTENTE INT NOT NULL,
    NAME VARCHAR(14) NOT NULL CHECK (CHAR_LENGTH(NAME) BETWEEN 4 AND 14),
    SURNAME VARCHAR(16) NOT NULL CHECK (CHAR_LENGTH(SURNAME) BETWEEN 4 AND 16),
    BIRTHDATE DATE NOT NULL,
    CREDIT DECIMAL(10,2) NOT NULL,
    ADDRESS VARCHAR(255),
    FOREIGN KEY (ID_UTENTE) REFERENCES UTENTI(ID)
);

CREATE TABLE IF NOT EXISTS MATERIALI (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(40) NOT NULL CHECK (CHAR_LENGTH(NOME) BETWEEN 10 AND 40),
    DESCRIZIONE VARCHAR(250),
    DATA DATE NOT NULL,
    QUANTITA INT NOT NULL,
    COSTO DECIMAL(10,2) NOT NULL,
    ID_UTENTE INT NOT NULL,
    FOREIGN KEY (ID_UTENTE) REFERENCES UTENTI(ID)
);

CREATE USER IF NOT EXISTS 'lettore'@'localhost' IDENTIFIED BY 'P@ssw0rd!';
CREATE USER IF NOT EXISTS 'modificatore'@'localhost' IDENTIFIED BY 'Str0ng#Admin9';

GRANT SELECT ON eco_scambio.* TO 'lettore'@'localhost';
GRANT ALL PRIVILEGES ON eco_scambio.* TO 'modificatore'@'localhost'; --GRANT SELECT, INSERT, UPDATE, DELETE ON eco_scambio.* TO 'modificatore'@'localhost';

FLUSH PRIVILEGES;

INSERT INTO UTENTI (NICK, PASSWORD, ARTIGIANO) VALUES
('marco123', '$2y$12$np75BC3Ypzb7gH9RcCg7Yun5Kf7P1eyrPrm2ZihBlflLncirvNjeq', TRUE),
('luca87', '$2y$12$LjGs8x5Sf4/iF1erpUPrqO/FMz7HlCYf8SIInffszEh0MxrqBqmxu', FALSE),
('giulia98', '$2y$12$LHbDNgJTjZPLH8TFDxwU/uU33BjA6/bAXgJJ4dLXu75HVCIKYmCum', TRUE),
('admin01', '$2y$12$nSKcjDMLpUoSrfi0G1bpkexlmrtL3iNPe8bjQHMbIVwRTKfrhfcoW', FALSE);

INSERT INTO DATI_AZIENDE (ID_UTENTE, RAGIONE, ADDRESS2) VALUES
(2, 'Tech Solution SRL', 'Via Industria 14, Milano'),
(4, 'SmartBuild SPA', 'Corso Italia 22, Torino');

INSERT INTO DATI_ARTIGIANI (ID_UTENTE, NAME, SURNAME, BIRTHDATE, CREDIT, ADDRESS) VALUES
(1, 'Marco', 'Ferrari', '1984-06-15', 1250.75, 'Via Roma 10, Napoli'),
(3, 'Giulia', 'Bianchi', '1990-11-30', 234.50, 'Via Dante 7, Bologna');

INSERT INTO MATERIALI (NOME, DESCRIZIONE, DATA, QUANTITA, COSTO, ID_UTENTE) VALUES
('Pannello Isolante 30mm', 'Materiale per isolamento termico/acustico', '2025-05-10', 150, 12.30, 2),
('Vernice Antiruggine Rossa', 'Vernice per metalli ad alta resistenza', '2025-04-22', 60, 8.45, 2),
('Cemento Rapido 25kg', 'Sacchi di cemento per lavori rapidi', '2025-05-01', 200, 4.90, 4),
('Tubi PVC 2m', 'Tubi da impianto idraulico', '2025-03-28', 340, 2.75, 4);

